.travis.yml, core/CMakeLists.txt, core/include/oneseismic/geometry.hpp, core/python/CMakeLists.txt, core/python/oneseismic/CMakeLists.txt, core/python/oneseismic/geometry.cpp, core/python/oneseismic/tests/test_geometry.py, core/python/requirements-dev.txt, core/python/setup.cfg, core/python/setup.py
The bulk of this patch is the build system (setup.py and cmake), which
are largely taken from ecl3 [1]. The oneseismic.geometry exposes the 3D
CS, FS, and GVT datatypes, and virtually no operations.
[1] https://github.com/equinor/ecl3
=> Add oneseismic.geometry python extension

protos/core.proto
Extra motovation for removing now is name collision as golang converts
camel_case to CamelCase
=> Remove unused protobuf code

core/src/manifest.cpp, core/src/worker.cpp, core/tests/fragment-task.cpp, core/tests/manifest-task.cpp
Message envelopes should be passed through allowing various message
routing schemes to be applied while leaving the internals of the
components oblivious to the messaging topology.
=> Forward message envelopes

core/src/manifest.cpp, core/src/worker.cpp
This was a bug causing failures when slicing in any dimension other than
the first.
=> Flatten slice direction in slice_layouts

core/tests/fragment-task.cpp
The test was not setting cube shape causing it to default to 0. This
does not affect the correctness of the test but it triggers an assertion
when compiled in Debug mode.
=> Fix faulty test

api/server/server_test.go
The server_test.go being a part of the top-level module might have been
the right choice at the time, but not anymore.
=> Move api/server-test into api/server module

core/ingestion/upload/upload/upload.py
Creating the container for every segment is a bug and will cause a
ResourceExistsError. Create container only once before uploading segments, 
and handle ResourceExistsError.
=> Create container before uploading segments

core/include/oneseismic/azure.hpp, core/src/azure.cpp, core/src/server-fragment.cpp, core/src/server-manifest.cpp, core/tests/azure-transfer-config.cpp, docker-compose.yml, radixconfig.yaml
Storage account is sent from the api and stored as batch.root. The
storage_account az member is not in use and is therefore removed.
=> Remove unused storage_account member

.github/workflows/ci.yaml
Reenable when tests are not flaky and are more complete.
Setting AZURE_STORAGE_ACCESS_KEY in manifest and core works from env
but not from docker-compose_test.yml. Depending on timings we
unpredictable results.
=> Turn off flaky integration tests in ci

api/server/sliceModel.go, core/include/oneseismic/tasks.hpp, core/src/manifest.cpp, core/src/server-manifest.cpp, core/tests/manifest-task.cpp
Split the set of fragment IDs into multiple separate tasks, to allow
fetch to run in parallel across multiple nodes. The task size is set a
priori, and is not dynamic, as it is not obvious that dynamic task
scalign will even be beneficial, or at least be worth it in terms of
complexity.
The resulting fragments are buffered and put in order at the session/api
node, so clients are unaware of the (possible) parallelism in task
fetch. This means unmodified clients will still work as expected.
Some error and failure signaling is glaringly missing, but as of now
there are no obvious places to signal and fail processes (particularly
in go). This is not made very much worse by parallel fragment tasks, so
it is acceptable for this change.
=> Partition fetch task

api/main.go, api/server/multiplexer.go, api/server/multiplexer_test.go, api/server/server.go, api/server/server_test.go, api/server/sliceController.go, api/server/sliceController_test.go, api/server/sliceModel.go, api/server/sliceModel_test.go, core/include/oneseismic/transfer.hpp, core/src/azure.cpp, core/src/manifest.cpp, core/src/server-fragment.cpp, core/src/server-manifest.cpp, core/src/worker.cpp, core/tests/azure-transfer-config.cpp, core/tests/testsuite.cpp, core/tests/transfer-http.cpp, docker-compose.yml, protos/core.proto
Map lookups in golang returns by value, not by reference, which means
updating the procstatus.completed array was broken. Fix this by storing
a pointer to a procstatus in the map, rather than the object itself.
This was not caught by any tests, since no tests yet used multi-task
processes. Extended the echoAsWorker with a tasks parameter, and
read expected results for the results-channel until it exhausts. This
was manually verified to fail (no-recv on the channel before timeout)
when storing procstatus as objects, not pointer-to-procstatus.
=> Add Sessions test for multi-task processes

api/generate.go
The swag and protoc-gen-go commands need to be installed during build.
Their versions should respect go.mod and go.sum.
The "go get" command gets the laste version of the package and updates
go.mod and go.sum
The "go install" command seem to behave correctly...
=> Do not upgrade packages when running go generate

api/auth/auth.go, api/go.mod, api/go.sum, api/main.go, api/server/multiplexer.go, api/server/sliceController.go, api/server/sliceModel.go
When running "go test -race ./..." the golog package cannot be used
inside goroutines. Uncertain if golog introduces race conditions during
runtime.
TODO: Consider aligning logging from iris if we continue to use iris.
=> Use a logger that does not create race conditions

docker-compose_tests.yml, tests/Dockerfile
Use pip to install packages in test
Require python 3.8 image for tests
=> Use pip to install oneseismic in tests

python/oneseismic/client/client.py, python/oneseismic/login/__main__.py, python/oneseismic/login/login.py, python/requirements-dev.txt, python/setup.cfg
Avoid polluting home directory by adhering to the xdg specification [1].
[1] https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html
=> Use XDG_CACHE_HOME for storing token

core/Dockerfile
The core/ docker image was obnoxiously large, upwards of 1.3G. This is
largely because the build image itself was a part of the final, which
includes development packages. Some fairly small changes pushes the size
down to approx 100M [1].
Two main changes push down the size:
1. Build artifacts are copied into a clean base image with only
runtime dependencies installed. This is the big driver.
2. What's build from source is statically linked.
[1] which is still massive, approx. the size of the api/ image, which is
what you would expect
=> Trim fat from core/ docker image

api/api/slice.go, api/cmd/query/main.go, docker-compose.yml, python/oneseismic/client/client.py, python/oneseismic/client/tests/client_test.py
Add a cube entry point that describes the available features for a cube,
and provide some basic metadata (for now, just the dimensions). The
dimension is re-introduced in Python through the more general cube.shape
attribute.
The implementation of slice.Entry is pretty rough - it does not really
belong on the Slice struct and is mostly copy-paste of the
fetch-and-parse logic from Slice.Get. It will certainly be refactored
quite soon, but is written as-is to highlight what exactly is (typical)
common code. Please note the absence of tests is with this in mind -
tests should be introduced with said refactoring.
=> Add entry endpoint /query/:guid and cube.shape

core/CMakeLists.txt, core/include/oneseismic/load_balancer.hpp, core/src/load_balancer.cpp, core/src/server-fragment.cpp, core/src/server-manifest.cpp, core/tests/load_balancer.cpp
Message broker that will distribute tasks to workers as they become
available.
The advantage of this approach over PUSH-PULL is that jobs are sent to
idle workers, whereas PUSH-PULL distributes round robin. A disadvantage
is that the queue becomes a single point of failure, and a single point
for all messages to pass through, while PUSH-PULL is N-to-N.
=> Add load balancing message broker

python/oneseismic/login/login.py
In the case that the base cache folder does not exists the current folder creation will fail as it is not recursive. Using os.makedirs with exist_ok=True fixes this issue without introducing additional dependencies.
This is a duplicate of #425 with updated commit messages
=> Update login.py with recursive folder creation

python/oneseismic/__init__.py, python/oneseismic/internal/argparse.py, python/oneseismic/internal/blobfs.py, python/oneseismic/scan/__main__.py, python/oneseismic/upload/__main__.py, python/setup.cfg
Scan and upload learnt to read input volumes as https://acc.storage/container/blob?sas=token, and supports single-blob signatures.
=> Blobfs sas token auth

api/api/result.go, api/cmd/fetch/fetch.go, api/cmd/query/main.go
Store results in redis as a single stream data structure rather than as
individual keys for each partial result. This has several benefits:
1. Stream offers blocking operations for waiting for results to be
ready
2. Dealing with a single datastructure for monitoring progress is more
ergonomic
3. Tests showed that stream performed better under high loads with
many workers writing partial results to storage concurrently.
=> Replace partial result keys with redis stream

python/oneseismic/internal/argparse.py, python/oneseismic/internal/blobfs.py, python/oneseismic/internal/test_argparse.py
The path/root argument in the localfs-from-args function was effectively
ignored, when it should be considered the root.
=> Respect root argument when making localfs

README.md, python/LICENSE, python/setup.cfg
The LGPL is a more suited license for the SDK and python programs. The
goal of the license is to keep oneseismic free software, but not
impose these restrictions on users of oneseismic data.
=> Relicense connector+python to LGPL-3+

api/api/graphql.go, api/cmd/query/main.go, api/go.mod, api/go.sum, python/oneseismic/client/client.py, python/requirements-dev.txt, python/setup.cfg
This is a very exciting feature, introduced with a terrible
implementation.
Motivation
----------
So why this change? When playing around with various scenarios and
client implementations, it became quite clear that what oneseismic
really is deep down is a database engine. What you quickly want from
that is proper user driven queries, which you can build on top of the
REST URL-maps-to-resource scheme, but is quite cumbersome.
For ease of implementation, the approach was to have a very simple
interface for queries (since it has to be mapped to the concept of "the
resource"), and let clients handle mapping from whatever structure they
had into dimension/lineo, array-of-pairs etc. The more I work on this
the more I realise that you want some server support for easy-to-write
queries too.
What …
=> Graphql endpoint

python/oneseismic/internal/argparse.py, python/oneseismic/internal/test_argparse.py
The localfs_from_args helper is used both when setting up input (usually
a file name) and output (usually a directory), but when used like this:
oneseismic scan file.sgy
it would try to open file.sgy/file.sgy, which is wrong. localfs supplies
open() and really work on directories, so infer the directory from the
path even when it is a file.
=> Always get directory in localfs_from_args

api/api/endpoint.go, api/api/graphql.go, api/api/scheduler.go, api/internal/message/message.go, api/internal/util/util.go, core/include/oneseismic/messages.hpp, core/include/oneseismic/plan.hpp, core/src/messages.cpp, core/src/plan.cpp, core/src/process.cpp, core/tests/messages.cpp, core/tests/process.cpp, python/oneseismic/client/client.py
The gist of this PR is that it moves input validation and transformation into C++, and cleans up some long-standing problems with the message format in exchange between the I/O and query system (in go) and the scheduler (in C++).
Almost-literally translated _queries_ are validated and assembled into _tasks_ in C++, which is now represented through distinct types. This brought along some nice simplification and fixed addressed some hygiene issues.
The patch set is built iteratively, but the understanding comes from messages.go and messages.hpp.
The slice() query is extended to sliceByLineno and sliceByIndex which interpret the parameters as line number and index respectively, giving the user the choice of reference system.
=> Refactor scheduling message format; extend slice() query

api/api/graphql.go, api/cmd/fetch/fetch.go, core/include/oneseismic/messages.hpp, core/src/messages.cpp, core/src/plan.cpp, core/tests/messages.cpp, python/oneseismic/upload/upload.py, python/setup.cfg
The manifest has for a very long time just been a copy of the scan
output, and used only to store the line numbers for a volume, but was
always intended to be the source of a richer set of parameters and
metadata. Since the rest of oneseismic has been too immature to leverage
a beefier manifest, it was never a priority, but we have reached the
point where it will be useful.
I would like to emphasize that I do not think this is a complete and
final "specification" for format-version 1, and that I expect a little
bit of a churn as we discover opportunities and problems.
Motivation
----------
This is a typical manifest so far:
{
"byteorder": "big",
"format": 1,
"samples": 5,
"sampleinterval": 5000,
"byteoffset-first-trace": 3600,
"guid": "c26ff223460fb33230d2cb17bd2cdb95",
"dimensions": [
[ …
=> Revised manifest and attributes

api/api/graphql.go, api/api/result.go, api/api/scheduler.cpp, api/api/scheduler.go, api/cmd/fetch/tasks.cpp, api/internal/message/message.go, core/CMakeLists.txt, core/include/oneseismic/geometry.hpp, core/include/oneseismic/geometry.impl.hpp, core/include/oneseismic/messages.hpp, core/include/oneseismic/plan.hpp, core/include/oneseismic/process.hpp, core/src/messages.cpp, core/src/plan.cpp, core/src/process.cpp, core/tests/geometry.cpp, core/tests/messages.cpp, core/tests/process.cpp, python/oneseismic/client/client.py, python/oneseismic/upload/upload.py
This PR adds support for attributes. Briefly, attributes are per-trace data, typically coordinates, that can be quite useful sometimes. The motivation is best illustrated with an example. Consider the query
```
{
cube(id: ...) {
sliceByLineno(dim: 0, index: 150, opts: { attributes: [cdp] })
}
}
```
When realised into an xarray, it yields
```
<xarray.DataArray 'inline 10261' (crossline: 720, time: 850)>
array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
...,
[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
-1.1615995e-02, …
```
=> Add attribute-query support

.travis.yml, api/api/result.go, api/api/scheduler.cpp, api/internal/message/message.go, core/include/oneseismic/messages.hpp, core/include/oneseismic/plan.hpp, core/src/messages.cpp, core/src/plan.cpp, core/src/process.cpp, core/tests/process.cpp, python/oneseismic/client/client.py, python/oneseismic/upload/upload.py
This PR comes with some performance improvements and hygiene stuff, but the big feature is *drastically* reducing the response message size for slices by using tuples over maps.
The message layout used until now had good library support and was quick and easy to get started with (nlohmann/json msgpack serialization), but made for terrible messages in system <-> system communication. This PR demonstrates the benefit of packing messages more deliberately, but is still not very bold, as it's not hooking into the msgpack ext-type system.
The patch provides strong value on its own, but is a step towards a streaming and C++-provided user-side message parsing.
---
Pack the slice response, tiles, as a sequence of tuples rather than a
sequence of maps. By using tuples the message size is …
=> Pack tiles as tuples

core/external/catch2/catch/catch.hpp
This is mostly a routine upgrade, and adds a fix for a runtime error on
the Apple M1.
unrecognized instruction mnemonic, did you mean: bit, cnt, hint,
ins, not?
=> Upgrade catch2 to 2.13.7

.github/workflows/ci.yaml, .github/workflows/wheels.yaml, Dockerfile, core/CMakeLists.txt, core/include/oneseismic/decoder.hpp, core/include/oneseismic/messages.hpp, core/src/decoder.cpp, core/src/messages.cpp, core/src/plan.cpp, core/src/process.cpp, python/CMakeLists.txt, python/oneseismic/client/client.py, python/oneseismic/decoder.cpp, python/pyproject.toml, python/requirements-dev.txt, python/setup.cfg, python/setup.py
There's actually a couple of (somewhat related) changes in this PR, but it brings two major improvements.
I measured the time taken by parse+extract _after_ all data was downloaded before and after this PR.
NEW
0.001031s
0.000731s
OLD
0.024170s
0.020067s
Which means that in parsing and extracting alone this brings 20-30x performance improvement.
The message format has been reviewed, and the (main) payload is no longer serialized as an array, but rather bin. The messagepack binary type is really just length + blob, and leaves the actual format to the application. In this case we know it's float32 little-endian, which brings down overhead (1 byte per element) and reduces serialization cost. Most of the performance improvements come from this change.
I've written a decoder in C++ that should …
=> Add decoder

api/api/result.go
This is a bug in the /result that's been there since it was written. It
accidentally worked when the failure channel was closed in collectResult
(which it shouldn't be).
err, ok := <-failure will block until there is a message on the channel
*or* it is closed, but its intention is to read a message if available,
otherwise just continue.
Replace it with a select { case ...; default } which actually has this
behaviour.
=> Don't do blocking read on failure channel

.github/workflows/wheels.yaml, python/pyproject.toml, python/setup.cfg
As far as I can tell, i686 wheels on linux are subtly broken since it
would re-use the dependencies built on amd64, since the dependency build
artefacts are not wiped between builds. Re-using built dependencies
between python versions is a good performance improvement, and simply
building in cibw-$arch/ rather than build/ is sufficient to make sure
the wheels are built correctly.
=> Respect arch in wheel

api/api/graphql.go, core/include/oneseismic/messages.hpp, core/src/decoder.cpp, core/src/messages.cpp, core/src/plan.cpp, python/oneseismic/client/client.py, python/oneseismic/decoder.cpp
Motivation
----------
The server has more information about the query and request than the
decoder and mapping to the user environment want to juggle, so add axis
labels (inline, crossline, time, depth etc) and shape hints to the
response.
Having this information in the message makes for a much nicer user
experience when decoding, since the decoder does no longer depend on
information from when the request was *made*. This gives the response
some interesting properties:
1. When distributing the results to worker nodes, they only need the
promise, since the response itself has enough information to make
proper sense of it. It makes workers easier to write and more
independent, since they can be reduced to simple response processers.
2. Much simpler decoding; get an instance, give it some …
=> Send allocation hints in response

api/api/graphql.go, python/oneseismic/client/client.py
Nullable promises
==============
Using optional return values makes for a less brittle API, since even
promises could be just a small part of a larger query. This has no
python client support as of now (hence the awkward for loop for
extraction), but the API might as well support it.
For a motivating example, consider this query:
cube(ids: $ids) {
year
sliceByLineno(dim: $dim, lineno: $lineno)
}
IDs would be a set of independent surveys in the same area (e.g. North
Sea), which would return a specific line across a large area from the
candidate surveys. If a line is not a part of the survey then it is
simply skipped. For good measure the year is included to weed out very
old surveys. This would not work if the query would error after the
first line without a survey.
Applications, such as …
=> Nullable and scalar promises

api/api/scheduler.cpp, core/src/messages.cpp, core/src/plan.cpp
Break up the scheduler_maker system into free overloaded functions. It
turns out that the generic algorithms can just as easily be written with
free templated functions, and the lookup rules through a class really
isn't used. Maybe shared-state-between-<type> will be useful at some
point in the future, but then that can rather be special-cased rather
than introducing heavy template machinery for the general case. This
benefit is a simplification.
All changes are really just in signatures; the schedule() and
partition() functions are free, and uses overloading to select the
correct build() and header() functions, rather than the class. Since the
selection was always derived only from the input- and output types then
there should be no real loss in flexibility.
The partition() and …
=> Break up the scheduler_maker system into free overloaded functions

core/CMakeLists.txt, core/src/decoder.cpp
Use C++17 fallthrough attribute instead of comment
--
Revert "Find and link msgpack with cmake"
This change is pretty broken, as it relies on newer versions of
libmsgpack [1], and was not thoroughly tested. It was doubly broken
since it did not actually link, but rather used the include-dir, and it
would not work for decoder-only builds.
Since we use the header-only feature relying on it being in an available
include path is good enough for now, although this bit of the makefiles
should probably be improved upon.
It was merged to make the macos CI build work again, but in this
particular broken instance the real fix was installing the msgpack-cxx
package; see commit 38487dc
[1] e.g. the target msgpackc-cxx is not found on my debian buster
(which provides 3.0.1-3)
=> Fallthrough attributes; revert msgpack-with-cmake

api/api/graphql.go, core/include/oneseismic/messages.hpp, core/src/decoder.cpp, core/src/messages.cpp, core/src/plan.cpp, core/src/process.cpp
Include the height/zlength in the curtain message, rather than assuming
it can be read from the index. This makes the decoding function more
obviousy and immediate (since it no longer needs to read the index), but
bloats the message with another byte or two per bundle (which I think
is an acceptable trade off).
On its own this change only makes the decoding slightly simpler, but
this opens up for decoding curtain attributes of non-trace-length in the
z direction.
Introduce the opts argument to the curtainBy* family of queries, and
support getting attributes along with data for the curtain query.
The implementation is pretty straight forward for the go bits; add opts
to the schema, and include the opts parameter in the message.Query.
The C++/query planning follows the pattern laid out by …
=> Attributes in curtain

javascript/CMakeLists.txt, javascript/LICENSE, javascript/README.md, javascript/build.sh, javascript/decoder.cpp, javascript/decoding.js, javascript/demo/demo-node.js, javascript/demo/demo.html, javascript/emscripten.dockerfile
Provide a javascript library for decoding oneseismic results. The
library itself is mostly the decoder compiled with emscripten, a little
bit of binding code, and some usability features. Please be aware that
the module itself is quite rough and needs a lot of love and testing.
Error paths in particular are not checked exhaustively (if at all).
Using oneseismic through the web browser (or even some other js runtime
like node) will be common, and native javascript decoding makes
client-side rendering fast and feasible.
With the library comes a couple of build scripts - driving the build
with cmake is quite painless, and the emscripten.dockerfile makes it
possible to run even without installing the emscripten sdk directly on
the host.
No testing hooks or testing strategy is included in the …
=> Add javascript support library

.github/workflows/wheels.yaml, python/pyproject.toml
The windows-2016 environment is deprecated and was removed as of April
1st, 2022 [1]. As a result, or CI pipeline have skipped the
wheelbuilding on windows since then. Upgrading environment also
requires a bump of the MSVC version from 15 -> 16.
[1] https://github.com/actions/virtual-environments/issues/5238
=> Build wheels using windows-2019 runner on gh

api/cmd/query/main.go, api/cmd/result/main.go, javascript/demo/demo-node.js, javascript/demo/demo.html
Doing a PR now in unlikely case it's useful in the next month.
No parseopt tests at the moment.
Looks like getopt package keeps defined command line options between tests and complains when parsopt is called second time. And I can't find a way to force tests reload.
That probably means that if this is to be tested, definition of command line args and parsing of args has to be splited, but I am not exactly there yet.
Regarding demos - I don't know how they work, but at least now they both print the same value to me for the same file :smile:
=> Setup update

api/catalogue/graphql.go, api/cmd/catalogue/main.go, api/internal/postgres/postgres.go
This PR does a couple of refactor / prep-commits, then introduces an Index / database facade that aims to hide the database transport / connection from the rest of the system. It's implemented as a go interface to allow mocking, which will make it easier to test the rest of the system without having a real connection.
=> Add an database abstraction 

core/src/messages.cpp, core/tests/messages.cpp
Motivation:
Quick fix to resolve compile error when using the following combination:
- C++20
- GCC 11.X
- fmt lib v8.1.1
The resulting errors are of the form
```
‘constexpr’ expansion of ‘fmt::v8::basic_format_string<char, int&>(msg)’
messages.cpp:354:36: error: the value of ‘msg’ is not usable in a constant expression
```
The error is resolved by changing the associated  msg declaration from **const** to **constexpr**
=> Change fmt msg string from const to constexpr

CONTRIBUTING.md, README.md, SECURITY.md
Update in accordance with Equinor SCM policy.
Prepare README.md for project rename.
=> Apply scm policy
