equinor/oneseismic

api/main.go

Otherwise errors when starting server will probably not show

Wait for logs to flush before exiting

---

api/cmd/config.go
api/cmd/config_test.go
api/cmd/serve.go
api/main.go

No longer possible to turn off in config

Auth always enabled

---

core/include/oneseismic/azure.hpp
core/include/oneseismic/tasks.hpp
core/include/oneseismic/transfer.hpp
core/src/azure.cpp
core/src/log.hpp
core/src/manifest.cpp
core/src/transfer.cpp
core/src/worker.cpp
core/tests/fragment-task.cpp
core/tests/manifest-task.cpp
core/tests/mhttpd.hpp
core/tests/transfer-http.cpp

Not quite merge ready, this is mostly for CI now.

Improvements

---

core/CMakeLists.txt
core/Dockerfile
core/src/server-fragment.cpp
core/src/server-manifest.cpp
docker-compose.yml

This is a rough sketch of a process for the manifest phase of a request.
It is in no way complete, but should run well enough to be somewhat
testable.

Add rough manifest+fragment binaries & docker-compose

---

api/server/sliceController.go

This should be passed through the entire flow the entire flow

Generate a uuid for requestid

---

api/auth/auth.go
api/main.go
docker-compose.yml
docker-compose_tests.yml

Only RS256 tokens are supported

Remove support for HS256 jwt tokens

---

api/server/multiplexer.go
api/server/sliceModel_test.go
core/src/manifest.cpp
core/src/worker.cpp

Just a fairly small set of clarifications, clean-ups to make functions flow better.

Prettifications

---

api/Dockerfile
api/auth/auth.go
api/auth/auth_test.go
api/main.go
api/server/server.go
api/server/server_test.go
docker-compose.yml
docker-compose_tests.yml
tests/integration/integration_tests.py

This PR prepares for sending storage endpoint url to core and using JWT to authenticate and authorize to the storage

Always check issuer and audience

---

core/src/worker.cpp
core/tests/fragment-task.cpp

The tile buffer was not cleaned up between requests causing tiles from
previous requests to be prepended to the response.

Clean up buffers between runs

---

api/api/result.go
api/api/result_test.go

Getting results from storage often means starting a lot of concurrent
downloads. Any of these downloads could fail, and a single failure means
the process as a whole should be cancelled.
The azblob package has built-in support for this by taking a context [1]
parameter, so just sharing this context among the sibling goroutines
should accomplish this.
Testing really then just boils down to making sure the cancel() signal
is actually called, as exactly how and when tasks are cancelled is
controlled by azblob. Manually performed experiments have shown that
sibling jobs return _, err where err is "cancelled" for the http
requests.
This only addresses the goroutine cancellations, and is not at all
sensitive to *why* a transfer failed. In practice, it is likely to be a
timing issue where the …

Share context and cancel signal in result/download

---

api/api/result.go
api/api/result_test.go
api/api/slice.go
api/cmd/query/main.go
api/cmd/relay/main.go
api/internal/auth/auth.go
api/internal/auth/auth_test.go
core/CMakeLists.txt
docker-compose.yml
python/oneseismic/client/client.py
python/setup.cfg

With queries being async, there has to be a mechanism in place that
makes sure results are not leaked, i.e. results are only available to
whoever requested the data.
The plan is to return a token which should be set in the authorization
header which provides (read) access to the process result and process
status. The creation, signing, and validation of these tokens is what
the Keychain provides.

Redis as storage

---

api/internal/auth/openid.go
api/internal/auth/openid_test.go
docker-compose_tests.yml
tests/integration_tests.py

Trying to make the integration tests run after major api update

Integration tests

---

README.md

Reboot readme

---

api/api/curtain.go
core/src/plan.cpp

Perform the validation of input in C++, and only relay parameters and
report errors from go. This is another step in the move to making go a
pure I/O driver, and having all geometry and query logic in C++. It is
also a step in the direction towards a well defined query planner.
The C++ library has better tooling, support and know-how built into it
for dealing with geometry. Building a proper query planner module is
then natural to do in C++, which has the added benefit of completely
separating the responsibilities of the go and C++ code - go does I/O,
http, session management and concurrency, and C++ parses and validates
user parameters, handles geometry and builds the (internal) messages for
the other components in oneseismic.
Implementation wise this should come with few surprises, but …

Validate request parameters in C++

---

api/cmd/fetch/fetch.go
api/cmd/fetch/fetch_test.go
api/cmd/fetch/main.go
docker-compose.yml

Controls MaxRetryRequests in RetryReaderOptions in call to Body() when
reading the BLOB. Default value of 0 disables retries.

Allow retries from blobstore.

---

api/api/graphql.go
core/src/messages.cpp
core/src/plan.cpp
python/oneseismic/client/client.py

Bring the curtain queries aware of different indexing schemes to match
the slice query.

Query curtain by index/lineno explicitly

---

python/oneseismic/upload/upload.py

This was causing the shape to be added twice.

Do not add shape string to prefix in manifest

---

api/api/scheduler.go
api/api/scheduler_test.go

This PR is really a bunch of long put off janitor work in the scheduler, and the addition of a couple of tests.

Clean up scheduler

---

core/src/messages.cpp
core/tests/messages.cpp

First part of messages tests because I remember someone complained that they were not tested enough.
I rewrote this many times ~because I am terrible at c++~ because I several times understood that my oneseismic understanding is wrong and because I struggled to make tests not too complex, but still maintainable and readable. I like current form the most of everything I tried.
I still might have misunderstood something somewhere, but my lonely local integration test passes, so it's probably fine.

Messages query tests

---

.github/workflows/azure.yaml
api/cmd/fetch/main.go
api/cmd/gc/main.go
api/cmd/query/main.go
api/cmd/result/main.go
deploy/create_support_structure.sh
deploy/fetch.bicep
deploy/main.bicep
deploy/nginx.Dockerfile
deploy/nginx.bicep
deploy/nginx.conf
deploy/support_structure.bicep
deploy/update.sh
docker-compose.yml
tests/Dockerfile
tests/test_integration.py

Basic Azure tests. Mostly, as it appeared, code that allows creation of server-side setup.
Many things are unclear but I think we can better figure them out in the future
1. Because _someone_ thinks it's acceptable to not review PRs for months, first commit contains the same things as an unmerged PR from 3 months ago. I am not bothering anymore if ports are strings, ints or whatever is merged first. :smiling_imp: 
2. Setup should be ready for testing if it would be useful in production, but can't yet be used on production data as resources are not approved yet (Container Apps are even still in preview). I put in the code distinction between test and production logic, but values are kinda random in both cases.
3. There will be certain changes in Container Apps during March (moving to App …

Azure tests and Deployment

---

.github/workflows/azure.yaml
.github/workflows/e2e.yaml
tests/docker-compose.local.yml

UPD 30.05
It worked on Friday... Main bug is fixed, but revision thing has problems again (main URL doesn't pick up active revision, though revision URL is working correctly)
I think it's a new bug. Previously behavior was a bit different.
And they also spoiled revision UI. Again, but this time in different place.
I am strongly considering doing workarounds for this part, but I am willing to give them a chance. If there is no bug for it during the week and they won't fix it until then, I'll submit a new issue.
UPD 01.06
As was unable to reproduce that on a fresh demo instance of contaier apps, recreated current ones from scratch. It works now, but shall see.

Small fixes for E2E setup

---

.github/workflows/azure.yaml
.github/workflows/e2e.yaml
tests/docker-compose.local.yml
tests/javascript/docker-compose.javascript.yml
tests/python/docker-compose.python.yml

Quick fixes to prevent current solution from everyday reporting failures to me and quick fixes of currently existing failures (as ofc azure job started failing last week because contain apps changed behavior yet again)
I am not happy that we need to revert to this and if not for our current shutdown I would have tried to ask devs again if that's a bug or a feature, but in current situation this is the easiest fix.

Remove jobs run on schedule
